null reference with error and no response
I was running into a scenario where the response object was null and I had one error. The problem was that the response log was being printed before the error's one. So I had the process crashing before I realized what the problem was. 

```
[FAILED] /dist/404.html -> /recife/404.html
//node_modules/gulp-s3/index.js:59
        gutil.log(gutil.colors.red('  HTTP STATUS:', res.statusCode));
                                                        ^

TypeError: Cannot read property 'statusCode' of undefined
   ...
```

I separated the log messages in two different conditions, so one problem won't fall into another.